version: "3.9"

name: complai-directus-nextjs-poc

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  directus:
    image: ${AZURE_REGISTRY_LOGIN_SERVER}/directus:${IMAGE_TAG}
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      DB_CLIENT: pg
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: ${CORS_ORIGIN}
      PUBLIC_URL: ${PUBLIC_URL}
    volumes:
      - directus_uploads:/directus/uploads
      - ./backend/extensions:/directus/extensions
    depends_on:
      - db

  frontend:
    image: ${AZURE_REGISTRY_LOGIN_SERVER}/frontend:${IMAGE_TAG}
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - directus

volumes:
  db_data:
  directus_uploads:
