name: Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    # Build and push Directus image
    - name: Build and push Directus
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.directus
        push: true
        tags: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/directus:${{ github.sha }}

    # Build and push Frontend image
    - name: Build and push Frontend
      uses: docker/build-push-action@v2
      with:
        context: ./apps/frontend
        file: ./apps/frontend/Dockerfile
        push: true
        tags: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }}

    # Deploy to Azure Container Apps
    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ secrets.AZURE_REGISTRY_NAME }}
        acrUsername: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        containerAppName: complai-app
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
        dockerComposeFile: docker-compose.prod.yml
